sudo: required
addons:
  postgresql: "9.6"

before_install:
- openssl aes-256-cbc -K $encrypted_fcc4dca47958_key -iv $encrypted_fcc4dca47958_iv -in secret.tar.enc -out secret.tar -d
- tar xvf secret.tar
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.6
- sudo apt-get install -qq libpq-dev

matrix:
  include:
  - language: c
    services: postgresql
    compiler: gcc
    before_script:
    - openssl aes-256-cbc -K $encrypted_fcc4dca47958_key -iv $encrypted_fcc4dca47958_iv -in secret.tar.enc -out secret.tar -d
    - tar xvf secret.tar
    - cd c
    - psql -c "CREATE DATABASE testdb;" -U postgres
    script:
    - make
  - language: python
    services: postgresql
    python:
    - '3.3'
    - '3.5'
    - '3.6'
    before_install:
    - export DJANGO_SETTINGS_MODULE="JobCaravan.settings"
    - export PYTHONPATH=$HOME/builds/bklo94/JobCaravan
    - export PIP_USE_MIRRORS=true
    install:
    - easy_install distribute
    - pip install -r python/requirements.txt
    - pip install django==$DJANGO --quiet
    - pip install psycopg2 --quiet
    before_script:
    - cd python
    - psql -c "CREATE DATABASE testdb;" -U postgres
    script:
    - python manage.py syncdb --noinput

notifications:
   email:
   - brandonklo94@gmail.com
