matrix:
  include:
  - language: c
    compiler:
    - gcc
    before_script:
    - cd c
    script:
    - "./make.sh"
notifications:
  email:
  - brandonklo94@gmail.com
before_install:
- openssl aes-256-cbc -K $encrypted_fcc4dca47958_key -iv $encrypted_fcc4dca47958_iv
  -in secret.tar.enc -out c/include/secret.tar -d
