sudo: required
dist: trusty

addons:
  postgresql: "9.4"
  apt:
    packages:
    - postgresql-9.4
    - postgresql-client-9.4
    - postgresql-server-dev-9.4
    - libpq-dev
    env:
    global:
    - PGPORT=5432
    - PGHOST=localhost

matrix:
  include:
  - language: c
    services: postgresql
    compiler: gcc
    before_install:
    - pg_config
    - openssl aes-256-cbc -K $encrypted_fcc4dca47958_key -iv $encrypted_fcc4dca47958_iv -in secret.tar.enc -out secret.tar -d
    - tar xvf secret.tar
    before_script:
    - cd c
    - psql -c "CREATE DATABASE testdb;" -U postgres
    script:
    - ./make.sh

  - language: python
    services: postgresql
    python:
    - '2.7'
    before_install:
    - pg_config
    - openssl aes-256-cbc -K $encrypted_fcc4dca47958_key -iv $encrypted_fcc4dca47958_iv -in secret.tar.enc -out secret.tar -d
    - tar xvf secret.tar
    - export DJANGO_SETTINGS_MODULE="mysite.settings"
    - export PYTHONPATH=$HOME/builds/bklo94/JobCaravan/python
    - export PIP_USE_MIRRORS=true
    install:
    - easy_install distribute
    - pip install -r python/requirements.txt --no-cache-dir
    - pip install psycopg2 --quiet
    before_script:
    - sudo /etc/init.d/postgresql restart
    - cd python
    - psql -c "CREATE DATABASE testdb;" -U postgres
    script:
    - python manage.py migrate --noinput
    - python manage.py inspectdb --noinput

notifications:
   email:
   - brandonklo94@gmail.com
