matrix:
  include:
  - language: c
    compiler:
    - gcc
    before_script:
    - cd c
    script:
    - make
  - language: python
    services: postgresql
    python:
    - '3.3'
    - '3.5'
    - '3.6'
    before_script:
    - cd python
    before_install:
    - export PIP_USE_MIRRORS=true
    install:
    - easy_install distribute
    - pip install -r requirements.txt
    before_script:
    - psql -c "CREATE DATABASE jobsdb;" -U bklo
    script:
    - python manage.py runserver"
notifications:
   email:
   - brandonklo94@gmail.com
before_install:
   - openssl aes-256-cbc -K $encrypted_fcc4dca47958_key -iv $encrypted_fcc4dca47958_iv -in secret.tar.enc -out secret.tar -d
   - tar xvf secret.tar
