sudo: required
dist: trusty

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6
    - postgresql-client-9.6
    - postgresql-server-dev-9.6
    - libpq-dev
    env:
    global:
    - PGPORT=5432
    - PGHOST=localhost
    - PQ_INCDIR=/usr/include/postgresql
    - PQ_LIBDIR=/usr/lib/x86_64-linux-gnu
    
before_install:
- pg_config
- openssl aes-256-cbc -K $encrypted_fcc4dca47958_key -iv $encrypted_fcc4dca47958_iv -in secret.tar.enc -out secret.tar -d
- tar xvf secret.tar

matrix:
  include:
  - language: c
    services: postgresql
    compiler: gcc
    before_script:
    - cd c
    - psql -c "CREATE DATABASE testdb;" -U postgres
    script:
    - make

  - language: python
    services: postgresql
    python:
    - '3.6'
    before_install:
    - export DJANGO_SETTINGS_MODULE="JobCaravan.settings"
    - export PYTHONPATH=$HOME/builds/bklo94/JobCaravan
    - export PIP_USE_MIRRORS=true
    install:
    - easy_install distribute
    - pip install -r python/requirements.txt
    - pip install django==2.0.4 --quiet
    - pip install psycopg2 --quiet
    before_script:
    - sudo /etc/init.d/postgresql restart
    - cd python
    - psql -c "CREATE DATABASE testdb;" -U postgres
    script:
    - python manage.py syncdb --noinput

notifications:
   email:
   - brandonklo94@gmail.com
