# Generated by Django 2.0.4 on 2018-04-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
                ('snippet', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('longitutde', models.FloatField(blank=True, null=True)),
                ('latitutde', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'indeed',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
